In [2]:
import tensorflow as tf
import pandas as pd

In [3]:
#Q1
"Broadcasting Mechanism"
a = tf.reshape(tf.range(4), (4, 1))
b = tf.reshape(tf.range(3), (1, 3))
a, b

(<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
 array([[0],
        [1],
        [2],
        [3]], dtype=int32)>,
 <tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[0, 1, 2]], dtype=int32)>)

In [4]:
a+b

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]], dtype=int32)>

In [ ]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Floor,Price,Clean,Status\n')  # Column names
    f.write('101,1,127500,NA,1\n')  # Each row represents a data example
    f.write('201,2,106000,1,0\n')
    f.write('301,3,178100,NA,1\n')
    f.write('NA,4,NA,1,0\n')
    f.write('501,5,155000,1,0\n')
    f.write('601,6,167000,0,1\n')
    f.write('701,7,185000,1,0\n')
    f.write('801,8,231000,1,1\n')
    f.write('NA,9,345000,NA,1\n')
    f.write('1001,10,456000,NA,NA\n')


In [ ]:
import pandas as pd
data = pd.read_csv(data_file)
data

In [ ]:
last_column = data.pop('Price')
data['Price'] = last_column
data


In [ ]:
#dropping this column as it has the most missing values
data.drop(['Clean'], axis=1, inplace=True)
data 

In [ ]:
inputs, outputs = data.iloc[:, 0:3], data.iloc[:, 3]
inputs = inputs.fillna(inputs.mean())
print(inputs)

In [ ]:
inputs = pd.get_dummies(inputs, dummy_na=True)
#inputs = np.asarray(inputs)
print(inputs)

In [ ]:
X, y = tf.constant(inputs.values), tf.constant(outputs.values)
X, y