In [1]:
import tensorflow as tf
import numpy as np

In [17]:
x = tf.range(12)
x1 = tf.reshape(x, (3, 4))
x2 = tf.reshape(x, (6, 2))
x3 = tf.reshape(x, (4, 3))
y = tf.range(24)
x4 = tf.reshape(y, (2, 3, 4))

In [18]:
x

<tf.Tensor: shape=(12,), dtype=int32, numpy=array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11], dtype=int32)>

In [19]:
x1

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int32)>

In [20]:
x2

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]], dtype=int32)>

In [21]:
x3

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]], dtype=int32)>

In [22]:
x4

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]], dtype=int32)>

In [23]:
print("Lengths, x: {}, x1: {}, x2: {}, x3: {}, x4: {}".format(len(x), len(x1), len(x2), len(x3), len(x4)))

Lengths, x: 12, x1: 3, x2: 6, x3: 4, x4: 2


In [38]:
print(tf.shape(np.sum(x4, 0)))
print(tf.shape(np.sum(x4, 1)))
print(tf.shape(np.sum(x4, 2)))

tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor([2 4], shape=(2,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)


In [39]:
np.linalg.norm(x4)

65.75712889109438

In [40]:
g = tf.random.Generator.from_seed(1234)
g1 = g.normal(shape=(2, 3, 3))
g2 = g.normal(shape = (3, 4, 3, 2))

In [41]:
g1

<tf.Tensor: shape=(2, 3, 3), dtype=float32, numpy=
array([[[ 0.9356609 ,  1.0854305 , -0.93788373],
        [-0.5061547 ,  1.3169702 ,  0.7137579 ],
        [-0.4126717 , -0.40257987,  2.0713255 ]],

       [[-0.35911667,  0.3861619 ,  1.9897066 ],
        [-0.2823396 , -0.5135972 , -0.8962833 ],
        [-0.0901652 , -0.73964226, -0.46269894]]], dtype=float32)>

In [42]:
g2

<tf.Tensor: shape=(3, 4, 3, 2), dtype=float32, numpy=
array([[[[ 0.6691036 ,  0.35458583],
         [-0.08412673, -0.27878118],
         [ 0.35518306,  0.45159343]],

        [[ 0.18356216,  0.9144571 ],
         [ 0.6256486 , -0.00717345],
         [ 0.07791339, -0.20130906]],

        [[ 0.69460756,  0.961497  ],
         [-1.0040257 , -1.5463829 ],
         [ 1.6493912 ,  0.38229913]],

        [[ 1.4606284 , -0.32792607],
         [-1.3684198 , -0.78216076],
         [-0.905839  , -0.56385887]]],


       [[[-1.5865449 , -0.5855774 ],
         [ 0.77494633, -0.7208057 ],
         [-1.5740228 , -0.8111003 ]],

        [[ 0.8374056 , -0.6009648 ],
         [-0.4404535 ,  2.9320223 ],
         [ 0.04532953, -0.06675196]],

        [[-0.26831955,  0.5518779 ],
         [-0.37353563, -0.03234363],
         [-1.435514  , -0.64928484]],

        [[ 0.33595282,  0.7278141 ],
         [ 0.21227004, -1.6652247 ],
         [-0.5206754 , -0.6569389 ]]],


       [[[-0.3234604 , -0.18375304],
 

In [43]:
np.linalg.norm(g1)

4.0260634

In [44]:
np.linalg.norm(g2)

8.10842